export interface ClassifiedListItem {
  id: string
  title: string
  category: 'for-sale' | 'free'
  price: string
  originalPrice?: string
  discount?: string
  location: string
  date: string
  image: string
  description?: string
}

export const MOCK_CLASSIFIEDS: ClassifiedListItem[] = [
  // ── For Sale ──
  { id: 'cl-1',  category: 'for-sale', title: '2022 Trek FX3 Disc Hybrid Bike — Excellent Condition',      price: '$850',   originalPrice: '$1,200', discount: '29%', location: 'Steinbach', date: 'Today',  image: '/classifieds/forsale-01-bike.jpg', description: 'Lightly used Trek FX3 Disc hybrid bike in great shape. Perfect for commuting or weekend rides. Hydraulic disc brakes, Shimano drivetrain. Includes kickstand and bell. Selling because I upgraded to a road bike.' },
  { id: 'cl-2',  category: 'for-sale', title: 'iPhone 15 Pro Max 256GB — Like New, Space Black',            price: '$1,100', originalPrice: '$1,399', discount: '21%', location: 'Steinbach', date: 'Today',  image: '/classifieds/forsale-02-iphone.jpg', description: 'iPhone 15 Pro Max in Space Black, 256GB storage. Screen protector since day one, no scratches. Battery health at 98%. Comes with original box, cable, and a clear case. Carrier unlocked.' },
  { id: 'cl-3',  category: 'for-sale', title: 'Sectional Sofa — Charcoal Gray, Like New',                   price: '$650',                                            location: 'Mitchell',  date: 'Mar 19', image: '/classifieds/forsale-03-sofa.jpg', description: 'Beautiful charcoal gray sectional sofa, purchased 8 months ago from Leon\'s. Smoke-free, pet-free home. Seats 5 comfortably. L-shape configuration. Must pick up.' },
  { id: 'cl-4',  category: 'for-sale', title: 'LG 55" OLED 4K Smart TV — Model C2 Series',                 price: '$800',   originalPrice: '$1,200', discount: '33%', location: 'Steinbach', date: 'Mar 18', image: '/classifieds/forsale-04-tv.jpg', description: 'LG C2 55" OLED TV in perfect condition. Stunning picture quality with deep blacks. 4K, 120Hz, Dolby Vision & Atmos. Includes original stand, remote, and wall mount bracket.' },
  { id: 'cl-5',  category: 'for-sale', title: 'Husqvarna 24" Two-Stage Snowblower — Runs Great',            price: '$1,200', originalPrice: '$1,600', discount: '25%', location: 'Grunthal',  date: 'Mar 17', image: '/classifieds/forsale-05-snowblower.jpg', description: 'Husqvarna 24-inch two-stage snowblower. Electric start, power steering. Clears snow like a champ. Serviced every season. Great for Manitoba winters. Selling because we moved to a condo.' },
  { id: 'cl-6',  category: 'for-sale', title: 'John Deere X350 Riding Lawnmower — 42" Deck',                price: '$3,200',                                            location: 'Steinbach', date: 'Mar 16', image: '/classifieds/forsale-06-mower.jpg', description: 'John Deere X350 with 42" Accel Deep mower deck. 18.5 HP engine, hydrostatic transmission. Under 200 hours. Well maintained with all service records. Includes mulch kit.' },
  { id: 'cl-7',  category: 'for-sale', title: 'Gaming PC — RTX 4070, Ryzen 9, 32GB RAM, 2TB SSD',          price: '$2,400', originalPrice: '$3,200', discount: '25%', location: 'Steinbach', date: 'Mar 15', image: '/classifieds/forsale-07-pc.jpg', description: 'Custom built gaming PC. NVIDIA RTX 4070 12GB, AMD Ryzen 9 7900X, 32GB DDR5 RAM, 2TB NVMe SSD. NZXT H510 case with RGB. Runs everything on Ultra. Built 6 months ago.' },
  { id: 'cl-8',  category: 'for-sale', title: 'KitchenAid Artisan Stand Mixer — Cherry Red, Lightly Used',  price: '$280',   originalPrice: '$550',   discount: '49%', location: 'Steinbach', date: 'Mar 14', image: '/classifieds/forsale-08-mixer.jpg', description: 'KitchenAid Artisan 5-quart stand mixer in Empire Red. Used maybe 10 times. Comes with flat beater, dough hook, wire whip, and pouring shield. Perfect for baking.' },
  { id: 'cl-9',  category: 'for-sale', title: 'Baby Stroller — Chicco Bravo, Grey, Excellent Condition',    price: '$180',                                            location: 'Mitchell',  date: 'Mar 13', image: '/classifieds/forsale-09-stroller.jpg', description: 'Chicco Bravo Quick-Fold stroller in grey. One-hand fold, adjustable canopy, storage basket. Compatible with Chicco KeyFit infant car seats. Clean, smoke-free home.' },
  { id: 'cl-10', category: 'for-sale', title: 'Golf Club Set — Callaway 14-Piece, Men\'s Right Hand',       price: '$550',   originalPrice: '$900',   discount: '39%', location: 'Grunthal',  date: 'Mar 12', image: '/classifieds/forsale-10-golf.jpg', description: 'Callaway Strata 14-piece golf set, men\'s right hand. Driver, 3-wood, 5-hybrid, 6-PW irons, putter, and bag. Great starter or intermediate set. Used two seasons.' },
  { id: 'cl-11', category: 'for-sale', title: 'Fender Stratocaster Electric Guitar — Sunburst, Hardcase',   price: '$700',   originalPrice: '$1,200', discount: '42%', location: 'Steinbach', date: 'Mar 11', image: '/classifieds/forsale-11-guitar.jpg', description: 'Fender Player Stratocaster in 3-Color Sunburst. Maple fretboard, Alnico V pickups. Excellent condition, no dings. Comes with hardshell case and extra set of strings.' },
  { id: 'cl-12', category: 'for-sale', title: 'NordicTrack Treadmill T 6.5 S — Foldable, Works Great',      price: '$450',   originalPrice: '$1,200', discount: '63%', location: 'Steinbach', date: 'Mar 10', image: '/classifieds/forsale-12-treadmill.jpg', description: 'NordicTrack T 6.5 S treadmill with iFit compatible display. 10% incline, 10 MPH max speed. SpaceSaver design folds up. Under 100 miles. Moving sale — must go this week.' },
  { id: 'cl-13', category: 'for-sale', title: 'PlayStation 5 Disc Edition + 2 Controllers + 5 Games',       price: '$650',   originalPrice: '$850',   discount: '24%', location: 'Steinbach', date: 'Mar 9',  image: '/classifieds/forsale-13-ps5.jpg', description: 'PS5 Disc Edition bundle. Includes 2 DualSense controllers (white + midnight black) and 5 games: Spider-Man 2, God of War Ragnarök, Horizon Forbidden West, Gran Turismo 7, Ratchet & Clank.' },
  { id: 'cl-14', category: 'for-sale', title: 'Winter Tires — 235/65R17 Michelin X-Ice, Set of 4',          price: '$480',   originalPrice: '$700',   discount: '31%', location: 'Mitchell',  date: 'Mar 8',  image: '/classifieds/forsale-14-tires.jpg', description: 'Set of 4 Michelin X-Ice Xi3 winter tires, size 235/65R17. About 70% tread remaining. Mounted on steel rims (5x114.3 bolt pattern). Fits most mid-size SUVs.' },
  { id: 'cl-15', category: 'for-sale', title: '14ft Pelican Kayak — Paddles Included, Barely Used',         price: '$900',                                            location: 'Grunthal',  date: 'Mar 7',  image: '/classifieds/forsale-15-kayak.jpg', description: 'Pelican Mustang 140XP kayak, 14 feet. Stable and comfortable for lakes and rivers. Adjustable seat, storage hatch. Used 3 times. Includes 2 paddles and roof rack J-cradles.' },
  { id: 'cl-16', category: 'for-sale', title: 'Weber Original Kettle BBQ — 22", Excellent Condition',       price: '$160',   originalPrice: '$300',   discount: '47%', location: 'Steinbach', date: 'Mar 6',  image: '/classifieds/forsale-16-bbq.jpg', description: 'Weber Original Kettle Premium 22-inch charcoal grill. Built-in lid thermometer, one-touch cleaning system. Used one summer. Includes cover, chimney starter, and bag of charcoal.' },
  { id: 'cl-17', category: 'for-sale', title: 'Solid Wood Dining Table + 4 Chairs — Farmhouse Style',       price: '$420',                                            location: 'Steinbach', date: 'Mar 5',  image: '/classifieds/forsale-17-diningtable.jpg', description: 'Rustic farmhouse dining table with 4 matching chairs. Solid pine wood, seats 6. Table is 60" x 36". A few minor marks add to the character. Pickup only.' },
  { id: 'cl-18', category: 'for-sale', title: 'NordicTrack Elliptical SE7i — Works Perfectly, Pickup Only', price: '$380',   originalPrice: '$900',   discount: '58%', location: 'Steinbach', date: 'Mar 4',  image: '/classifieds/forsale-18-elliptical.jpg', description: 'NordicTrack SE7i elliptical trainer. 24 resistance levels, iFit Bluetooth. Smooth, quiet operation. Display shows time, distance, calories, heart rate. Heavy unit — bring help for pickup.' },

  // ── Free ──
  { id: 'cl-19', category: 'free', title: 'Moving Boxes — Various Sizes, Clean & Sturdy',               price: 'FREE', location: 'Steinbach', date: 'Today',  image: '/classifieds/free-01-boxes.jpg', description: 'About 20 moving boxes in various sizes (small, medium, large). All clean and sturdy, used once. Also have packing paper and bubble wrap. Must take all. Porch pickup.' },
  { id: 'cl-20', category: 'free', title: 'Firewood — Split & Dried, Must Pick Up',                     price: 'FREE', location: 'Grunthal',  date: 'Today',  image: '/classifieds/free-02-firewood.jpg', description: 'Pile of split firewood, mostly poplar and birch. Dried for one summer. Great for campfires or fire pit. Bring your own truck and load up. First come, first served.' },
  { id: 'cl-21', category: 'free', title: 'Garden Soil & Compost Bags — 8 Bags Available',              price: 'FREE', location: 'Steinbach', date: 'Mar 19', image: '/classifieds/free-03-soil.jpg', description: '8 bags of garden soil and compost mix, unopened. Bought too much for our garden project. Sitting in the garage. Come grab what you need.' },
  { id: 'cl-22', category: 'free', title: "Kids' Toys — Assorted Plastic Toys & Stuffed Animals",       price: 'FREE', location: 'Mitchell',  date: 'Mar 18', image: '/classifieds/free-04-toys.jpg', description: 'Big bin of kids\' toys — action figures, toy cars, stuffed animals, building blocks. All clean and in good shape. Ages 3-8. Kids outgrew them. Take the whole bin.' },
  { id: 'cl-23', category: 'free', title: 'Leftover Paint Cans — Various Colors, Half Full',            price: 'FREE', location: 'Steinbach', date: 'Mar 17', image: '/classifieds/free-05-paint.jpg', description: 'Several half-used cans of interior latex paint. Colors: beige, light gray, white, sage green. Great for touch-ups or small projects. All lids sealed tight.' },
  { id: 'cl-24', category: 'free', title: 'Potted Houseplants — Spider Plants & Pothos, 6 Available',   price: 'FREE', location: 'Steinbach', date: 'Mar 16', image: '/classifieds/free-06-plants.jpg', description: '6 healthy houseplants in pots — 3 spider plants and 3 golden pothos. Propagated from our collection. Easy to care for, great for beginners. Pots included.' },
  { id: 'cl-25', category: 'free', title: 'Lumber & Wood Planks — Assorted Sizes, Garage Cleanout',    price: 'FREE', location: 'Steinbach', date: 'Mar 15', image: '/classifieds/free-07-lumber.jpg', description: 'Assorted lumber from a deck project — 2x4s, 2x6s, plywood scraps. Various lengths. Some pressure-treated. Good for small projects. In the driveway, take what you need.' },
  { id: 'cl-26', category: 'free', title: 'Terracotta Flower Pots — Various Sizes, 20+ Available',     price: 'FREE', location: 'Mitchell',  date: 'Mar 14', image: '/classifieds/free-08-pots.jpg', description: 'Over 20 terracotta pots in various sizes, from 4" to 14". Some have minor chips but all functional. Great for spring planting. Stacked on the patio — come take your pick.' },
  { id: 'cl-27', category: 'free', title: 'Used Paperback Books & Magazines — Box of 40+',              price: 'FREE', location: 'Steinbach', date: 'Mar 13', image: '/classifieds/free-09-books.jpg', description: 'Box of 40+ paperback novels and magazines. Mix of fiction, mystery, romance, and non-fiction. Some bestsellers in there. Take the whole box — great for cottage reading.' },
  { id: 'cl-28', category: 'free', title: 'Baby Clothes — Newborn to 12M, All Clean, Box of 30+',      price: 'FREE', location: 'Grunthal',  date: 'Mar 12', image: '/classifieds/free-10-babyclothes.jpg', description: 'Box of 30+ baby clothes, newborn to 12 months. Mix of onesies, sleepers, outfits. All washed and clean, no stains. Gender neutral and boy styles. Smoke-free home.' },
  { id: 'cl-29', category: 'free', title: 'Old Microwave — Works Fine, Just Upgrading',                 price: 'FREE', location: 'Steinbach', date: 'Mar 11', image: '/classifieds/free-11-microwave.jpg', description: 'Panasonic countertop microwave, about 5 years old. Works perfectly fine — all buttons, turntable, light work. We just bought a new over-the-range model. Clean inside and out.' },
  { id: 'cl-30', category: 'free', title: 'Concrete Patio Stones — 20+ Pieces, Must Take All',         price: 'FREE', location: 'Steinbach', date: 'Mar 10', image: '/classifieds/free-12-patiostones.jpg', description: '20+ square concrete patio stones, 12"x12". Removed from old patio. Stacked in the backyard. Must take all — don\'t want to deal with leftovers. Bring a truck.' },
  { id: 'cl-31', category: 'free', title: 'Rolled Sod — Fresh Cut, About 30 Rolls, Pickup Today',      price: 'FREE', location: 'Mitchell',  date: 'Mar 9',  image: '/classifieds/free-13-sod.jpg', description: 'About 30 rolls of fresh sod, leftover from a landscaping project. Needs to go today or tomorrow before it dries out. Sitting on a pallet in the front yard.' },
  { id: 'cl-32', category: 'free', title: 'Christmas Decorations — Box of Ornaments, Lights & Tinsel', price: 'FREE', location: 'Steinbach', date: 'Mar 8',  image: '/classifieds/free-14-xmasdeco.jpg', description: 'Two large boxes of Christmas decorations — ornaments, string lights, tinsel, wreaths, and a tree skirt. Everything works. Downsizing our holiday collection.' },
  { id: 'cl-33', category: 'free', title: 'Garden Hose + Hand Tools — Old but Working',                 price: 'FREE', location: 'Grunthal',  date: 'Mar 7',  image: '/classifieds/free-15-gardenhose.jpg', description: '50ft garden hose (no kinks), hand trowel, cultivator, and pruning shears. All old but still get the job done. Free to anyone who needs them. On the front porch.' },
  { id: 'cl-34', category: 'free', title: 'Gravel & Landscaping Stones — Pile in Driveway, Free Pickup', price: 'FREE', location: 'Steinbach', date: 'Mar 6', image: '/classifieds/free-16-gravel.jpg', description: 'Pile of pea gravel and landscaping stones in the driveway. Removed from an old garden bed. Estimate about 1 cubic yard total. Bring buckets or wheelbarrow.' },
  { id: 'cl-35', category: 'free', title: 'Wooden Bookshelves — 2 Units, Solid Wood, Some Wear',       price: 'FREE', location: 'Steinbach', date: 'Mar 5',  image: '/classifieds/free-17-shelves.jpg', description: 'Two solid wood bookshelves, each about 6ft tall x 3ft wide. Some wear and scratches but sturdy and functional. Could be sanded and repainted. In the garage.' },
  { id: 'cl-36', category: 'free', title: 'Moving Blankets & Padding — 10+ Pieces, Garage Cleanout',   price: 'FREE', location: 'Mitchell',  date: 'Mar 4',  image: '/classifieds/free-18-blankets.jpg', description: 'Over 10 moving blankets and furniture pads. Some thick quilted, some thinner. All clean. Great for moving or protecting floors during projects.' },
]
